default: &default

 payment_methods:
  - A&R conversion
  - Card-Credit
  - Card-Debit
  - Cash
  - Cheque
  - ClassPass
  - Fitternity
  - Google Pay
  - Instamojo
  - NEFT
  - Not paid
  - PayTM

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
