default: &default

 payment_methods:
  - A&R conversion
  - Card-Credit
  - Card-Debit
  - Cash
  - Cheque
  - ClassPass
  - Fitternity
  - Google Pay
  - Instamojo
  - NEFT
  - Not applicable
  - Not paid
  - Paid to instructor
  - PayTM

 gst_rate:
  - 18

 attendance_statuses:
  - booked
  - attended
  - cancelled early  
  - cancelled late
  - no show

 attendance_status_client_cant_modify:
  - attended
  - cancelled late
  - no show

 attendance_status_does_count:
  - booked
  - attended
  - cancelled late
  - no show

 attendance_status_doesnt_count:
  - cancelled early

 attendance_status_cant_rebook:
  - booked
  - attended
  - no show

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
