default: &default

 payment_methods:
  - A&R conversion
  - Card-Credit
  - Card-Debit
  - Cash
  - Cheque
  - ClassPass
  - Fitternity
  - Google Pay
  - Instamojo
  - NEFT
  - Not applicable
  - Not paid
  - Paid to instructor
  - PayTM

 gst_rate:
  - 18

 attendance_statuses:
  - booked
  - attended
  - cancelled early
  - cancelled late
  - no show

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
